/* Generated By:JJTree: Do not edit this line. ClassDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY= */
package main;

public class ClassDecl extends SimpleNode {
  public ClassDecl(int id) {
    super(id);
  }

  public ClassDecl(Test p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=52cf2bb40885c3fd974f11ded7173246 (do not edit this line) */
