/* Generated By:JJTree: Do not edit this line. ClassDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY= */
public class ClassDecl extends SimpleNode {
  public ClassDecl(int id) {
    super(id);
  }

  public ClassDecl(Test p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b7584215c6afd4487b699fc612d5be29 (do not edit this line) */
