/* Generated By:JJTree: Do not edit this line. Program.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY= */
public class Program extends SimpleNode {
  public Program(int id) {
    super(id);
  }

  public Program(Test p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f7684af545fe164322569187ede35834 (do not edit this line) */
