/* Generated By:JJTree: Do not edit this line. Program.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY= */
package main;

public class Program extends SimpleNode {
  public Program(int id) {
    super(id);
  }

  public Program(Test p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=feab4c72aee8b6de81f653ded9231f19 (do not edit this line) */
