/* Generated By:JavaCC: Do not edit this line. TestTreeConstants.java Version 4.1d1 */
public interface TestTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECL = 1;


  public String[] jjtNodeName = {
    "Program",
    "ClassDecl",
  };
}
/* JavaCC - OriginalChecksum=adc6fe2694087dc750866f05592d28fd (do not edit this line) */
