/* Generated By:JavaCC: Do not edit this line. TestTreeConstants.java Version 4.1d1 */
package main;

public interface TestTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECL = 1;


  public String[] jjtNodeName = {
    "Program",
    "ClassDecl",
  };
}
/* JavaCC - OriginalChecksum=d99d18c29e4f338320554efe8bb69bc3 (do not edit this line) */
